### ISSUE TITLE
Update How to run ACCESS-ESM

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/access-hive.org.au#628]
Update how to run ESM with new repo (https://github.com/coecms/access-esm)
and check that it works.

**Comment by penguian** [comment]
The restart files used by [access-esm/config.yaml at pre-industrial · coecms/access-esm · GitHub](https://github.com/coecms/access-esm/blob/pre-industrial/config.yaml) are inconsistent with the `pre-industrial` configuration. See https://forum.access-hive.org.au/t/run-access-esm-fails-with-error-code-139/1749/18
See also https://forum.access-hive.org.au/t/should-access-nri-fork-https-github-com-coecms-access-esm/1796

Since the [current instructions](https://github.com/ACCESS-NRI/access-hive.org.au/blob/main/docs/models/run-a-model/run-access-esm.md ) are incorrect, a note should be added at the top to say that the instructions do not yet work and are undergoing revision.

**Comment by atteggiani** [comment]
The problem with the instructions is relative to the configuration itself. 
Who is taking care of this matter?
I think this should be something that gets solved rather quickly, so I would not add any note on the Hive instructions.
I'd rather speed up the process to solve the issue.
