### ISSUE TITLE
Update Bureau of Meteorology logo on Hive Docs banner

### ISSUE THREAD

**Issue by heidinett** [ACCESS-NRI/access-hive.org.au#727]
## Description
Need to change/revert back to standard Bureau logo on the Hive Docs banner

## Why
The Bureau have confirmed the logo we use in the main website is the one we should use. They have a new one (the map of Australia with the weather lines) that they use in social media and external engagement, but when you put it with other logos, it gets lost, so they asked us to not use. 

## Close Criteria
Reinstate standard Bureau logo.

**Comment by KAUR1984** [comment]
Thanks @heidinett ! On it now.

**Comment by KAUR1984** [comment]
For the implementation, I have created a folder called `footer-logos` to store all the footer-related images under `assets`. Haven't moved the other ones yet, since it is out of scope for this issue (will create a new refactoring issue for that). I have replaced the bom image with the standard stacked version in `.png` format. Preference was `.svg` format as it is a vector format, however no image is rendered when I choose the `.svg` format. Currently looking into this, however, to tick off the high priority issues before the workshop, happy for this one to be merged in development for now, so we have something in place.
