### ISSUE TITLE
UI: Add a quick banner at the top for advertising workshop

### ISSUE THREAD

**Issue by KAUR1984** [ACCESS-NRI/access-hive.org.au#747]
## Description
Add an advertising banner at the top of hive docs for the access community 2024 workshop. 

## Why
In case users land at hive page, they have a quick link to learn more about the access community 2024 workshop. 

## Close Criteria
- [ ] Add a banner at the top of the hive docs possibly before the workshop.

**Comment by paigem** [comment]
Could I request that we have a banner for the Training Day as the more prominent link? Since we are housing Training Day material on Hive Docs, I'd like a quick link to the Training Day page to be very visible from the home page of Hive Docs. 😊 

We could either have two banners, the first one for the Training Day, the second one for the workshop, or include links to both websites within the same banner (in which case I'd just ask that the Training Day is the most visible, at least for the next ~4 days! 😅).
